version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - {{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t gcr.io/unified-academy-252221/liberia:latest .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

      - save_cache:
          key: {{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      - run:
          name: Push docker image to GCE
          command: |
            docker push gcr.io/unified-academy-252221/liberia:latest

