version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - "docker-{{ .Branch }}"
          paths:
            - /caches/app.tar

      - restore_cache:
          keys:
            - "pip-{{ .Branch }}"
          paths:
            - /app/.cache/

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: Build application Docker image
          command: >
            docker build
            --cache-from=${DOCKER_IMAGE}:${DOCKER_TAG}
            -t ${DOCKER_IMAGE}:${DOCKER_TAG} .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar ${DOCKER_IMAGE}:${DOCKER_TAG}

      - save_cache:
          key: "docker-{{ .Branch }}-{{ epoch }}"
          paths:
            - /caches/app.tar

      - save_cache:
          key: "pip-{{ .Branch }}-{{ epoch }}"
          paths:
            - /app/.cache/

      - run:
          name: Push docker image to GCE
          command: |
            docker push ${DOCKER_IMAGE}:${DOCKER_TAG}

