# Generated by Django 2.2.5 on 2019-10-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20190911_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('biology', 'BIOLOGY'), ('chemicals', 'CHEMICALS'), ('chemistry', 'CHEMISTRY'), ('miscellaneous', 'MISCELLANEOUS'), ('physics', 'PHYSICS'), ('safety', 'SAFETY')], default='miscellaneous', max_length=256),
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[('LD', 'LD'), ('USD', 'USD')], default='LD', max_length=16)),
                ('notes', models.CharField(max_length=32)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.Item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
        ),
    ]
